apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics-service
  namespace: cloud-native-ai-hrms
spec:
  selector:
    app: kube-state-metrics
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  type: ClusterIP
