apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: cloud-native-ai-hrms
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
